### ISSUE TITLE
Repository Naming Issue

### ISSUE THREAD

**Issue by pixlhero** [himanshusharma89/arcore_example#2]
Isn't this repository an example on how to use the [ar_flutter_plugin](https://pub.dev/packages/ar_flutter_plugin)? And not just ARCore? ARKit is also supported.

**Comment by himanshusharma89** [comment]
Hi @pixlhero, this repository is an example of using the ar_flutter_plugin. What is the issue here?

**Comment by pixlhero** [comment]
it's called arcore_example. in my opinion it should be called ar_flutter_example or similar. or at least adapt the readme so it doesn't just say 'ARCore'.

**Comment by himanshusharma89** [comment]
Oh sure, will update the readme instead of breaking the link on blog, thanks @pixlhero
